name: Build Image

on:
  schedule:
    # At 10:15 UTC each day.
    - cron:  '15 10 * * *'

  pull_request: {}
  push:
    branches:
      - master
    tags:
      - v*

  release:
    types:
      - published

jobs:
  build:

    env:
      V1PI_VERSION: ${{ github.event_name == 'release' && github.event.release.tag_name || 'unstable' }}

    name: v1pi-build-${{ matrix.hotspot }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false # Allow all jobs to finish building
      matrix:
        hotspot:
          - hotspot
          - no-hotspot

    steps:

    - name: Update Dependencies
      run: sudo apt-get update

    - name: Install Dependencies
      run: sudo apt-get install -y coreutils p7zip-full qemu-user-static

    - name: Checkout CustomPiOS
      uses: actions/checkout@v4
      with:
        repository: 'guysoft/CustomPiOS'
        path: CustomPiOS

    - name: Checkout Project Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}
        path: repository
        submodules: true

    - name: Download Raspbian Image
      run: cd repository/src/image && wget -q -c --trust-server-names 'https://downloads.raspberrypi.org/raspios_lite_armhf_latest'

    - name: Update CustomPiOS Paths
      run: cd repository/src && ../../CustomPiOS/src/update-custompios-paths

    - name: Set the hotspot mode
      run: cd repository/src && echo export HOTSPOT=${{ matrix.hotspot }} > hotspot.sh

    - name: Build Image
      run: sudo modprobe loop && cd repository/src && sudo bash -x ./build_dist

    - name: Copy Output
      run: cp ${{ github.workspace }}/repository/src/workspace/*-raspios-bullseye-armhf-lite.img "v1pi-${{ env.V1PI_VERSION }}-${{ matrix.hotspot }}".img

    - name: Zip Output
      run: zip -prq "v1pi-${{ env.V1PI_VERSION }}-${{ matrix.hotspot }}".zip "v1pi-${{ env.V1PI_VERSION }}-${{ matrix.hotspot }}".img

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: v1pi-${{ env.V1PI_VERSION }}-${{ matrix.hotspot }}
        path: v1pi-${{ env.V1PI_VERSION }}-${{ matrix.hotspot }}.img

    - name: Upload img to release
      if: ${{ github.event_name == 'release' }}
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: v1pi-${{ env.V1PI_VERSION }}-${{ matrix.hotspot }}.zip
        asset_name: v1pi-${{ env.V1PI_VERSION }}-${{ matrix.hotspot }}.zip
        asset_content_type: application/zip
